version: "3"
services:
  wordpress:
    image: wordpress:4.9-php5.6-apache
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_PASSWORD: "secret"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
  loadbal:
    image: nginx:1.15
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
